### ISSUE TITLE
Images are very dark 

### ISSUE THREAD

**Issue by REPTILEHAUS** [tsigel/identity-img#1]
images are generating but they appear very dull or dark even with background color white set, is there any way to improve visibility of them

<img width="328" alt="screen shot 2018-03-30 at 14 15 56" src="https://user-images.githubusercontent.com/4680621/38137467-06b9d81a-3425-11e8-94e6-693649f070bb.png">

**Comment by tsigel** [comment]
Please provide an example id from which you generate images.
